parameters: {}
environment: {}
packages:
    - name: holidays
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: refresh
          binary: false
          main: "main"
          runtime: python:3.11
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits:
            timeout: 30000
            memory: 256
